[common]
build_flags = -Wall -g -Og
monitor_speed = 115200

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    https://github.com/hatchjaw/QNEthernet#2a120a02b74c5b1a2a38572f3c4e93408b7106c0
