[common]
build_flags = -Wall -g -Og
monitor_speed = 115200

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    https://github.com/hatchjaw/QNEthernet#2a59d8c7702d0c76dca4b125da481c6b941c1289
